/**
 * Tether's tuning: the constants behind the physics, in one place. Use these defaults, or override any of them; developer
 * tools can edit them live (TUNING_OPTIONS describes each one for a control). The four force settings (center,
 * repel, link strength, link distance) multiply into these.
 */
export const PHYSICS_TUNING = Object.freeze({
  // The force simulation: the layout's final polish, and the Floating mode.
  repelScale: 70,
  centerScale: 0.03,
  linkScale: 0.9,
  structureScale: 1.1,
  velocityDecay: 0.4,
  theta: 0.9,
  alphaMin: 0.001,
  levelGap: 24,
  ticksSmall: 300,
  ticksMedium: 200,
  ticksLarge: 120,
  // Floating: how hot the simulation runs while a node is held, how fast it cools afterwards, and whether a new
  // graph floats into place (animated) instead of appearing settled.
  dragHeat: 0.3,
  cooling: 0.0228,
  floatIn: true,
  // Floating in stops after this many ticks (about 4 s at 60 fps) even if the graph hasn't gone still: crowded
  // graphs can jitter at the drag heat for good, and the animation would never end.
  floatInTicks: 240,
  // Floating graphs are run at the drag heat until they're still (moving less than this per tick, or for at most
  // this many ticks, or this much work: node count × ticks), so grabbing a node disturbs only what's near it. Work,
  // not time, so the result doesn't depend on the machine.
  stillness: 0.02,
  settleTicks: 4000,
  settleWork: 1350000,
  softCollision: 0.3,
  // Elastic: stiffness = base + per-link × Link strength; anchor = base + per-center × Center.
  elasticStiffnessBase: 0.3,
  elasticStiffnessPerLink: 1,
  elasticAnchorBase: 0.05,
  elasticAnchorPerCenter: 0.5,
  elasticDamping: 0.35,
  elasticAlongHold: 2,
  elasticWake: 0.05,
  elasticRest: 0.01,
});

/** Controls for developer tools: { key, label, group, min, max, step, hint } (a boolean when min is undefined). */
export const TUNING_OPTIONS = [
  {
    group: "Simulation",
    key: "repelScale",
    label: "Repel scale",
    min: 0,
    max: 300,
    step: 1,
    hint: "Repel setting → force. Many-body push between every pair (Barnes-Hut).",
  },
  {
    group: "Simulation",
    key: "centerScale",
    label: "Center scale",
    min: 0,
    max: 0.2,
    step: 0.001,
    hint: "Center setting → pull toward the graph's own middle.",
  },
  {
    group: "Simulation",
    key: "linkScale",
    label: "Link scale",
    min: 0,
    max: 3,
    step: 0.01,
    hint: "Link setting → spring toward the link distance.",
  },
  {
    group: "Simulation",
    key: "structureScale",
    label: "Structure scale",
    min: 0,
    max: 5,
    step: 0.05,
    hint: "Pull toward each node's level (tree) or ring (radial).",
  },
  {
    group: "Simulation",
    key: "velocityDecay",
    label: "Velocity decay",
    min: 0.05,
    max: 0.95,
    step: 0.01,
    hint: "Friction: share of speed lost per tick.",
  },
  {
    group: "Simulation",
    key: "theta",
    label: "Barnes-Hut θ",
    min: 0.2,
    max: 2,
    step: 0.05,
    hint: "Accuracy vs speed of the repulsion: lower is exact and slower.",
  },
  {
    group: "Simulation",
    key: "alphaMin",
    label: "Alpha min",
    min: 0.0001,
    max: 0.05,
    step: 0.0001,
    hint: "The simulation stops when its temperature falls below this.",
  },
  {
    group: "Simulation",
    key: "levelGap",
    label: "Level gap",
    min: 0,
    max: 120,
    step: 1,
    hint: "Minimum clear space between neighbouring levels (px).",
  },
  {
    group: "Simulation",
    key: "ticksSmall",
    label: "Ticks < 300",
    min: 10,
    max: 1000,
    step: 10,
    hint: "Ticks to settle a new layout under 300 nodes.",
  },
  {
    group: "Simulation",
    key: "ticksMedium",
    label: "Ticks < 1000",
    min: 10,
    max: 1000,
    step: 10,
    hint: "… under 1,000 nodes.",
  },
  {
    group: "Simulation",
    key: "ticksLarge",
    label: "Ticks ≥ 1000",
    min: 10,
    max: 1000,
    step: 10,
    hint: "… 1,000 nodes and over.",
  },
  {
    group: "Floating",
    key: "dragHeat",
    label: "Drag heat",
    min: 0,
    max: 1,
    step: 0.01,
    hint: "Temperature held while a node is dragged: how much the rest of the graph sways.",
  },
  {
    group: "Floating",
    key: "cooling",
    label: "Cooling",
    min: 0.001,
    max: 0.2,
    step: 0.001,
    hint: "How fast it cools after you let go (per tick).",
  },
  {
    group: "Floating",
    key: "floatIn",
    label: "Float into place",
    hint: "New graphs settle live from their seed layout instead of appearing settled.",
  },
  {
    group: "Floating",
    key: "stillness",
    label: "Stillness",
    min: 0.001,
    max: 2,
    step: 0.001,
    hint: "A floating graph counts as settled once no node moves more than this per tick (at the drag heat).",
  },
  {
    group: "Floating",
    key: "settleTicks",
    label: "Settle ticks",
    min: 0,
    max: 5000,
    step: 50,
    hint: "The most ticks spent bringing a floating graph to rest.",
  },
  {
    group: "Floating",
    key: "floatInTicks",
    label: "Float-in ticks",
    min: 0,
    max: 3600,
    step: 30,
    hint: "The most ticks a new floating graph spends floating into place before it's brought to rest.",
  },
  {
    group: "Floating",
    key: "settleWork",
    label: "Settle work",
    min: 0,
    max: 10000000,
    step: 50000,
    hint: "The most work (nodes × ticks) spent bringing a floating graph to rest before showing it (very big graphs may still drift a little when grabbed).",
  },
  {
    group: "Floating",
    key: "softCollision",
    label: "Soft collision",
    min: 0,
    max: 1,
    step: 0.01,
    hint: "How hard overlapping nodes push apart while floating (as a push on their speed, so the graph can rest).",
  },
  {
    group: "Elastic",
    key: "elasticStiffnessBase",
    label: "Stiffness base",
    min: 0,
    max: 2,
    step: 0.01,
    hint: "How firmly links keep their shape, before Link strength.",
  },
  {
    group: "Elastic",
    key: "elasticStiffnessPerLink",
    label: "Stiffness × link",
    min: 0,
    max: 3,
    step: 0.05,
    hint: "Added per unit of the link force setting.",
  },
  {
    group: "Elastic",
    key: "elasticAnchorBase",
    label: "Anchor base",
    min: 0,
    max: 1,
    step: 0.01,
    hint: "How firmly nodes hold their place, before Center.",
  },
  {
    group: "Elastic",
    key: "elasticAnchorPerCenter",
    label: "Anchor × center",
    min: 0,
    max: 2,
    step: 0.05,
    hint: "Added per unit of the center force setting.",
  },
  {
    group: "Elastic",
    key: "elasticDamping",
    label: "Damping",
    min: 0.02,
    max: 0.95,
    step: 0.01,
    hint: "Share of speed lost per step: low wobbles, high is sluggish.",
  },
  {
    group: "Elastic",
    key: "elasticAlongHold",
    label: "Level hold",
    min: 1,
    max: 10,
    step: 0.1,
    hint: "Trees: how much more firmly nodes keep their level than their place along it.",
  },
  {
    group: "Elastic",
    key: "elasticWake",
    label: "Wake distance",
    min: 0.001,
    max: 5,
    step: 0.001,
    hint: "How far a node must be displaced before it disturbs its neighbours.",
  },
  {
    group: "Elastic",
    key: "elasticRest",
    label: "Rest threshold",
    min: 0.0005,
    max: 1,
    step: 0.0005,
    hint: "Below this speed and force a node is settled (and sleeps).",
  },
];

/** Ticks to settle a new layout: fewer for big graphs (repel is O(n log n) per tick). */
export function ticksFor(nodeCount, tuning = PHYSICS_TUNING) {
  return nodeCount < 300
    ? tuning.ticksSmall
    : nodeCount < 1000
      ? tuning.ticksMedium
      : tuning.ticksLarge;
}
